# Generated by Django 5.2.6 on 2025-10-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puclished_date',
            new_name='published_date',
        ),
    ]
